# Generated by Django 3.2.4 on 2021-06-27 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modification date and time')),
                ('category', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Customer Payments and Cheques'), (2, 'Financial Institution Transfers'), (3, 'Treasury Markets - Foreign Exchange, Money Markets and Derivatives'), (4, 'Collections and Cash Letters'), (5, 'Securities Markets'), (6, 'Treasury Markets - Commodities'), (7, 'Documentary Credits and Guarantees/Standby Letters of Credit'), (8, 'Travellers Cheques'), (9, 'Cash Management and Customer Status')], default=1)),
                ('type_name', models.CharField(max_length=64, unique=True)),
                ('purpose', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'message_type',
            },
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modification date and time')),
                ('file_name', models.CharField(max_length=128)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Processing in progress'), (2, 'File processed')])),
                ('file_content', models.TextField()),
            ],
            options={
                'db_table': 'source_file',
            },
        ),
        migrations.CreateModel(
            name='SwiftField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modification date and time')),
                ('key_mt_tag', models.CharField(blank=True, max_length=16)),
                ('field_tag', models.CharField(max_length=16)),
                ('field_name', models.CharField(max_length=64)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Mandatory'), (2, 'Optional')])),
                ('content_options', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('message_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swift_fields', to='swift_parsing_app.messagetype')),
            ],
            options={
                'db_table': 'swift_field',
                'ordering': ['message_type_id', 'field_tag'],
            },
        ),
        migrations.CreateModel(
            name='SwiftFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modification date and time')),
                ('field_value', models.CharField(max_length=512, null=True)),
                ('swift_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swift_values', to='swift_parsing_app.swiftfield')),
            ],
            options={
                'db_table': 'swift_field_value',
            },
        ),
        migrations.CreateModel(
            name='SwiftMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modification date and time')),
                ('transaction_id', models.UUIDField()),
                ('direction', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Incoming'), (2, 'Outgoing')])),
                ('message_content', models.TextField()),
                ('basic_header', models.CharField(blank=True, max_length=64, null=True)),
                ('application_header', models.CharField(blank=True, max_length=64, null=True)),
                ('message_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swift_messages', to='swift_parsing_app.messagetype')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swift_messages', to='swift_parsing_app.sourcefile')),
            ],
            options={
                'db_table': 'swift_message',
            },
        ),
        migrations.CreateModel(
            name='SwiftFieldValueDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modification date and time')),
                ('detailed_value', models.CharField(max_length=512, null=True)),
                ('swift_field_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swift_detailed_values', to='swift_parsing_app.swiftfieldvalue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='swiftfieldvalue',
            name='swift_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swift_values', to='swift_parsing_app.swiftmessage'),
        ),
    ]
