# Generated by Django 3.2.4 on 2021-06-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_parsing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiftmessage',
            name='transaction_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
